apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: custom-aman
  description: The is my second yaml
  labels:
    example.com/custom: custom_label_value
  annotations:
    example.com/service-discovery: artistweb
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - php,
  links:
    - url: https://www.google.com/
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: public-websites
